apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-api
  labels:
    app.kubernetes.io/name: demo-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
